CityFix/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :users do
    get "/users/sign_in" => "tickets/recentes"
  end

resources :votes do
  resources :tickets
    collection do
      post 'createe'
      delete 'destroy'
      delete 'byebye'

    end
  end

  resources :users do
    resources :tickets
    collection do
      get 'info'
      get 'password'
      get 'image'
      get 'perfil'
      put 'update_info'
      put 'update_image'
      put 'delete_image'

    end
  end

  resources :tickets do
    resources :votes
    collection do
      get 'list_all'
      get 'testing'
      get 'submetidos'
      get 'validados'
      get 'populares'
      get 'recentes'
    end
  end

  get 'welcome/index'

  root 'welcome#index'

end

CityFix/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController


            #landing page
 	def index
                        #example of a ticket with the most recent ticket submited
                        @Ticket = Ticket.find_by_sql(["select tickets.* from tickets order by created_at asc"]).first


	 	if user_signed_in?
	 		redirect_to :controller => 'tickets', :action => 'recentes'

	 	end

	end
end

CityFix/app/helpers/welcome_helper.rb
module WelcomeHelper

	 def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
end

CityFix/app/views/welcome/index.html.erb
<%= stylesheet_link_tag "homepage" %>
<%= stylesheet_link_tag "tickets" %>

<div class="container">

	<div class="container-top col-md-12 text-center">
		<div class="col-md-6 container-logo">
			<div class="col-md-5">
			<%= image_tag("logo.png", class: "img-responsive") %>
			</div>
			<div>
				<h1>City Fix</h1>
			</div>

			<div >
				<h4>Help us helping you!</h4>
			</div>
		</div>

		<% if user_signed_in? %>
		<div class="col-md-6 login-form hideit">
		<% else %>
		<div class="col-md-6 login-form">
		<% end %>
			<%= form_for :user, url: 'users/sign_in', html: {class: "form-horizontal "} do |f| %>
				<div class="form-group">
				    <%= f.label :email , 'Email', class: 'col-md-3 control-label pull-left' %>
					<div class="col-md-9">
				    	<%= f.email_field :email, autofocus: true , class: 'form-control' %>
				    </div>
				 </div>

				<div class="form-group">
					    <%= f.label :password , 'Password' , class: 'col-md-3 control-label pull-left'%>
					    <div class="col-md-9">
					    <%= f.password_field :password, autocomplete: "off" , class: 'form-control' %>
			    	</div>
				</div>



				  <% if Devise.mappings[:user].rememberable? -%>
				    <div class="field">
				      <%= f.check_box :remember_me %>
				      <%= f.label :remember_me, 'Lembrar-me' %>
				    </div>
				  <% end -%>

				  <div class="actions">
					  <button type="submit" name="commit" class="btn btn-default btn-sbmt">
					    Autenticar
					</button>
				  </div>
			<% end %>

		<div class="login-btns btn-panel">
		  <button type="button" id="login-reg"class="btn btn-default btn-gtop">Registar</button>
		  <button type="button" id="login-rec"class="btn btn-default btn-gtop">Recuperar Password</button>
		</div>

		</div>

		<div class="col-md-6 register-form hideit">
			<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: {class: "form-horizontal "}) do |f| %>
			  <%= devise_error_messages! %>

				<div class="form-group">
				    <%= f.label :fname,'Primeiro nome', class: 'col-md-3 control-label pull-left' %>
				    <div class="col-md-9">
				    	<%= f.text_field :fname, autofocus: true , class: 'form-control'%>
				  	</div>
				</div>

				<div class="form-group">
				    <%= f.label :lname,'Último nome', class: 'col-md-3 control-label pull-left' %>
				    <div class="col-md-9">
				    	<%= f.text_field :lname, autofocus: true , class: 'form-control' %>
				  	</div>
				</div>

			  <div class="form-group">
			    <%= f.label :email, 'Email', class: 'col-md-3 control-label pull-left' %>
			    <div class="col-md-9">
			    	<%= f.email_field :email, autofocus: true , class: 'form-control'%>
		  		</div>
		  	</div>

			  <div class="form-group">
			    <%= f.label :password , 'Password', class: 'col-md-3 control-label pull-left' %>
			    <% if @minimum_password_length %>
			    <em>(<%= @minimum_password_length %> characters minimum)</em>
			    <% end %>
			    <div class="col-md-9">
			    	<%= f.password_field :password, autocomplete: "off" , class: 'form-control' %>
			    </div>
			  </div>

			  <div class="form-group">
			    <%= f.label :password_confirmation, 'Confirmar password', class: 'col-md-3 control-label pull-left' %>
			    <div class="col-md-9">
			    	<%= f.password_field :password_confirmation, autocomplete: "off" , class: 'form-control'%>
			    </div>
		  	</div>

			  <div class="actions">
			    <button type="submit" name"commit" class="btn btn-default btn-sbmt">
					    Registar
				</button>
			  </div>
			<% end %>


			<div class="register-btns btn-panel">
			  <button type="button" id="reg-login"class="btn btn-default btn-gtop">Autenticar-me</button>
			</div>


		</div>

		<% if user_signed_in? %>
		  <div class="col-md-6 logout-form">
		<% else %>
		  <div class="col-md-6 logout-form hideit">
		  	<% end %>
			  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
		</div>


		<div class="col-md-6 recover-form hideit">
			<%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post }) do |f| %>
			  <%= devise_error_messages! %>

			  <div class="field">
			    <%= f.label :email %><br />
			    <%= f.email_field :email, autofocus: true %>
			  </div>

			  <div class="actions">

			  	<button type="submit" name"commit" class="btn btn-default btn-sm">
				    Enviar-me instruções para recuperar password
				</button>

			  </div>
			<% end %>

			<div class="recover-btns btn-panel">
			  <button type="button" id="rec-login"class="btn btn-default btn-sm">Autenticar-me</button>
			</div>


		</div>

	</div>
		<div class="container1 col-md-12 text-center container-m">
				<div class="col-md-12 ">


					<div >
						<h3>CityFix is a social app that makes people feel and live more their own city.
						Using this application users will be able to help fixing some of their city problems.
						 For example, a person walks through the same streets everyday and detects the same
						  problems without being fixed (broken water pipes, missing traffic signs, etc).
						  By using the application the user can upload a picture of that problem and it
						  will be redirected to the responsible authorities. The person can upload the
						  pic using our web app or when it gets home on its personal computer.*</h3>
					</div>
			</div>
		</div>


		<div class="col-md-12 container-mobile">
			<div class="col-md-4 ">
				<div class="text-center">
					<h1>Anywhere</h1>
					<h1>Desktop + Mobile</h1>

				</div>
		</div>

			<div class="col-md-8 container-logo">
				<div>
					<%= image_tag("Untitled-1234.png", class: "img-responsive") %>
				</div>
			</div>
		</div>

		<div class="col-md-12 container-mobile">

			<div class="col-md-8 container-logo">

			<% if !@ticket.nil? %>
			<div class="col-md-12 ticket">

					  <div class="col-md-12 ticket-container">

						<div class="col-md-12 ticket-title-container t-margin">
						  <div class="col-md-8 ticket-title">
							<div class="ticket-title2 t-dark-blue"><%= @Ticket.title %></div>
							<div class="t-soft-blue ticket-location"><%= @Ticket.location %></div>
						  </div>
						  <div class="col-md-1 pull-right ">
							<% if @Ticket.status_id ==0 %>
							   <%= image_tag("staus-red.png", class: "img-responsive",style:"") %>
							<%else %>
							  <%= image_tag("status-blue.png", class: "img-responsive",style:"") %>
							<%end%>
						  </div>
						</div>

						<div  class="col-md-12 ticket-image">

						  <%= image_tag("tickets/#{@Ticket.picture}", class:"img-responsive") %>
						  <!--<a href="tickets/#{ticket.id}"><%= image_tag("tickets/#{@Ticket.picture}", class: "img-responsive") %></a>-->
						</div>


						<div class="col-md-12 ticket-info t-margin t-nomargin">
						  <div class="col-md-6 ticket-owner-image">
							<div class="col-md-1 t-nomargin">


							  <%= image_tag("#{@Ticket.user.picture}", class: "img-circle img-responsive") %>
							  <!--<img src="img/default.png" alt="" class="img-circle img-responsive">-->
							</div>
							<div class="col-md-8 ticket-owner-name text-left t-dark-blue t-nomargin"><%= @Ticket.user.fname %> <%= @Ticket.user.lname %></div>
						  </div>
						  <div class="col-md-6 ticket-date text-right t-dark-blue"> <%= @Ticket.date%></div>
						</div>


						<div class="col-md-12 ticket-description">
						  <p><%=@Ticket.description%></p>
						</div>


						<div class="col-md-12 ticket-validations t-dark t-margin" data-valid="<%=@Ticket.id%>" data-validn="<%=@Ticket.votes.count%>")>
						  <%= @Ticket.votes.count %> validações
						</div>
					  </div>


			</div>
			<% end %>
			</div>



		<div class="col-md-4 container-pad-top ">
				<div class="text-center">
					<h1>Simple UI</h1>
				</div>
			</div>
		</div>




			<div class="container5 col-md-12 container-team text-center">
						<div>
							<h1>Team:</h1>
							<h4>Cristóvão Silva</h4>
							<h4>Georgina Esteves</h4>
						</div>

						<div >
							<h4>Márcio Fontes</h4>
							<h4>Ricardo Castro</h4>
							<h4>Tiago Miranda</h4>
						</div>
					</div>

</div>


<script>

	$("#login-reg").click(function(){
		$(".login-form").addClass("hideit");
		$(".register-form").removeClass("hideit");
	});


	$("#reg-login").click(function(){
		$(".register-form").addClass("hideit");
		$(".login-form").removeClass("hideit");
	});

	$("#login-rec").click(function(){
		$(".login-form").addClass("hideit");
		$(".recover-form").removeClass("hideit");
	});

	$("#rec-login").click(function(){
		$(".recover-form").addClass("hideit");
		$(".login-form").removeClass("hideit");
	});


/*
	$( "#sign_up").click(function() {

			var email = $("#inputEmail3").val();
			var password = $("#inputPassword3").val();

			$.ajax({
				url: '/users',
				type: "POST",
				beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
				data: { user: { email: email, password: password, password_confirmation: password  }},
				success: function(response){
					console.log(response);
				}
			});
		});

	$( "#login").click(function() {

		var email = $("#inputEmail").val();
		var password = $("#inputPassword").val();
		var remember = $("#remember").val();

		$.ajax({
			url: '/users/sign_in',
			type: "POST",
			beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
			data: { user: { email: email, password: password, remember_me: 1}},
			success: function(response){
				console.log(response);
			}
		});
	});

*/
/*
	$( "#logout").click(function() {


		$.ajax({
			url: '/users/sign_out',
			method: "DELETE",
			beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
			success: function(response){
				console.log("logged out");
			}
		});
	});
*/

</script>